// Generated by CoffeeScript 1.4.0
(function() {

  $(document).ready(function() {
    var body, changePage, currentClass, nav, offsetHeight, pagePos, pages, updateNav;
    nav = $('.main-nav li a[href^="#"]');
    offsetHeight = 147;
    currentClass = 'current';
    body = $('body');
    pages = $('.content');
    pagePos = {};
    $.each(pages, function(i, el) {
      var id;
      el = $(el);
      id = el.attr('id');
      return pagePos[id] = {
        pos: el.offset().top - offsetHeight
      };
    });
    nav.on('click', function(e) {
      var page;
      e.preventDefault();
      page = $(this).attr('href');
      return changePage(page);
    });
    changePage = function(page) {
      var newPage, offset, props;
      newPage = $("" + page);
      offset = newPage.offset().top - offsetHeight;
      updateNav(page);
      props = {
        scrollTop: offset
      };
      return $('html,body').animate(props, 1000);
    };
    return updateNav = function(page) {
      nav.removeClass(currentClass);
      return $('a[href="' + page + '"]').addClass(currentClass);
    };
  });

}).call(this);
